### ISSUE TITLE
Signup for new volunteer is currently broken

### ISSUE THREAD

**Issue by joseph-p-pasaoa** [Briahana-Mauge/CapstoneGroup1#95]
Clicking Sign Up button at bottom of filled-out sign up Volunteer form returns
**Feedback: Error: (500) userQueries.addUser is not a function**.

Database is not changed

Server console logs:
`TypeError: (500) userQueries.addUser is not a function
------ DETAILS:
    at Object.addVolunteer (/Users/joeyp/Code/_repos/capstone__FSWeb/backend/queries/volunteers.js:190:44)
    at signupVolunteer (/Users/joeyp/Code/_repos/capstone__FSWeb/backend/routes/auth.js:89:33) 
====== END Details ======`

Browser console logs:
`xhr.js:178
POST http://localhost:3008/api/auth/volunteer/signup 500 (Internal Server Error)`

**Comment by AminesCodes** [comment]
Thank you for outlining that issue @joseph-p-pasaoa 
This happened because or a circular module dependencies where the `query/users` was requiring `queries/admin`, `queries/fellows` and `queries/volunteers` and each of these files was requiring `queries/users` again
This has been addressed on PR#96, once approved this issue can be closed
